# Generated by Django 2.0.4 on 2018-04-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='email',
            field=models.EmailField(default='jacool92@gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='gift',
            name='occupied',
            field=models.BooleanField(default=0),
        ),
    ]
