# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-23 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20180420_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='link',
            field=models.URLField(max_length=100),
        ),
    ]
