# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-25 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20180424_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
