# Generated by Django 2.0.4 on 2018-04-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20180425_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
