# Generated by Django 2.0.4 on 2018-04-26 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20180426_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='email',
        ),
    ]
